#!/usr/bin/env bash
does_it_need_git_pull() {
    set -e # stop for when error occured

    # it from https://stackoverflow.com/questions/3258243/check-if-pull-needed-in-git
    UPSTREAM=${1:-'@{u}'}
    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse "$UPSTREAM")
    BASE=$(git merge-base @ "$UPSTREAM")

    # echo "LOCAL: ${LOCAL}"
    # echo "REMOTE: ${REMOTE}"
    # echo "BASE: ${BASE}"

    RESULT=""
    if [ $LOCAL == $REMOTE ]; then
        RESULT="Up-to-date"
    elif [ $LOCAL == $BASE ]; then
        RESULT="Need to pull"
    elif [ $REMOTE == $BASE ]; then
        RESULT="Need to push"
    else
        RESULT="Diverged"
    fi

    echo ${RESULT}
}
